version: '3'

services:
  geo-postgres:
    build: ./db/.
    container_name: geo-postgres
    environment:
      POSTGRES_PASSWD: "postgres"
      database: mgis
      user: postgres
      password: postgres
      psqlPort: 5432
      psqlHost: 0.0.0.0
      # PG_CONF: "max_connections=100#listen_addresses='*'#shared_buffers=128MB#dynamic_shared_memory_type=posix#log_timezone='UTC'#datestyle='iso, mdy'#timezone='UTC'#log_statement='all'#log_directory='pg_log'#log_filename='postgresql-%Y-%m-%d_%H%M%S.log'#logging_collector=on#client_min_messages=notice#log_min_messages=notice#log_line_prefix='%a %u %d %r %h %m %i %e'#log_destination='stderr'#log_rotation_size=500MB#log_error_verbosity=default"
    ports:
      - "5432:5432"
    volumes:
      - ${LOCAL_DATABASE}:/data
      - ./import_data:/data_import
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@vizzuality.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - geo-postgres
    networks:
      - postgres-compose-network

  redis:
        image: redis:4
        ports:
            - 6379:6379
        networks:
          - postgres-compose-network

  api-vl:
    container_name: api-vl
    build: .
    ports:
      - "5100:5100"
    volumes:
      - ./app:/mgis/app
    command: develop
    restart: always
    environment:
      PORT: 5100
      HOST: "0.0.0.0"
      database: mgis
      user: postgres
      password: postgres
      psqlPort: 5432
      psqlHost: "geo-postgres"
      REDIS_CACHE: "redis://localhost:6379/0"
    depends_on:
    - geo-postgres
    - pgadmin
    - redis
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge